# Generated by Django 4.2.3 on 2023-07-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Имя')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('info', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
